spring.security.oauth2.client.registration.google.client-id=874238140539-c2bu6jbg0cb5vmgfkuqqkit67ti0f96m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email